### ISSUE TITLE
Broken build caused by alpine edge package

### ISSUE THREAD

**Issue by geichelberger** [opencast/opencast-docker#107]
At the moment it is not possible to build the docker images for the opencast version 6.2.
The reason is that the alpine edge repository does not contain the version 62 of libicui18n but version 63.

> ERROR: unsatisfiable constraints:
>  so:libicui18n.so.62 (missing):
>    required by: tesseract-ocr-4.0.0-ro[so:libicui18n.so.62]
> ...

I had a similar problem with the images of oc version 5.

Isn't it better to use the stable alpine version?

**Comment by mtneug** [comment]
Thank you for the report. I cannot reproduce the issue, but I have seen dependency problems in the past. You are right, edge is not the ideal version, but the only one that had all dependencies for Synfig, which is used by Opencast.

The decision for Alpine was primarily for simplicity and size, but maybe I will have a look at other distributions that package a version of synfig directly in their repository.

**Comment by miesgre** [comment]
@mtneug Synfig builds in alpine:3.9 

I tried to build this Dockerfile (https://github.com/mtneug/synfig-core-docker/blob/master/Dockerfile#L1) changing alpile:edge by alpine:3.9 and it builds

**Comment by mtneug** [comment]
Starting with `6.4` the images now use `openjdk:8-jdk-slim-stretch` which in turn is based on Debian. I only use the stable repository. Installed packages are not the newest (ffmpeg and tesseract 3 instead of 4), but it should be more stable. If you find any problems with the new images, please open an issue.
