### ISSUE TITLE
Docker reports Opencast images as Unhealthy

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast-docker#112]
Docker reports the opencast images as unhealthy, using the command

```bash
$ docker inspect --format='{{json .State.Health}}' <container-name>
```
This command shows that in all opencast nodes the problem comes from this line:
 
`/docker-healthcheck.sh: 17: set: Illegal option -o pipefail\n`

**Comment by mtneug** [comment]
Thank you.

Please note that you have to take the health check with a grain of salt. It will report Opencast as unhealthy as soon as one service fails even when it is recoverable. We therefore currently do not use this information in our production environment. I hope this will improve with a better script and [MH-13515](https://opencast.jira.com/browse/MH-13515).

**Comment by mliradelc** [comment]
Thanks @mtneug to take care of this 😄
