### ISSUE TITLE
Event not showing after created 

### ISSUE THREAD

**Issue by sirmadboy** [opencast/opencast-docker#131]
Hi,
I managed to deploy opencast-docker on my server. but when I add event, it didn't show in events list. Although the video that I uploaded showed on the media module. 
I'm using `quay.io/opencast/allinone:8.2`image and using mysql database.
ddl got from  [here](https://raw.githubusercontent.com/opencast/opencast-docker/8.2/docker-compose/assets/opencast-ddl.sql).

**Comment by mtneug** [comment]
I did a quick test using `docker-compose` and couldn't reproduce your problem:

```sh
$ docker-compose -p opencast-allinone -f docker-compose/docker-compose.allinone.mariadb.yml up
```

This is probably not a problem with the Docker images but rather with configuration or ActiveMQ. I would suggest posting to the [Opencast users mailing list](https://groups.google.com/a/opencast.org/forum/#!forum/users) and also describe your setup/problem in more details.

**Comment by sirmadboy** [comment]
okay, thank you for your help.
