### ISSUE TITLE
Question about distribution Dockerfiles

### ISSUE THREAD

**Issue by lbjay** [opencast/opencast-docker#161]
This is a question rather than an issue. I have not examined every Dockerfile, but for at least a few of them the differences seem very insignificant, e.g., changes to an env var and label metadata. I'm wondering why the project chooses to maintain so many separate, mostly redundant, files, vs some kind of base image and/or build args.

**Comment by mtneug** [comment]
This has historical reasons. We used to build images directly on Docker Hub and later Quay.io. There it is (was?) limited what you can pass as build arguments.

I will reopen as now with GitHub actions we can consolidate the `Dockerfiles`. I'm already doing that for my internal images anyway.
