### ISSUE TITLE
Some ENV variables required but unused

### ISSUE THREAD

**Issue by jojoob** [opencast/opencast-docker#163]
The docker images for the worker and presentation node require you to set the following variables although the configuration is not needed on this nodes:

* ACTIVEMQ_BROKER_URL
* ACTIVEMQ_BROKER_USERNAME
* ACTIVEMQ_BROKER_PASSWORD
* ELASTICSEARCH_SERVER_HOST

On omitting the following [error is shown](https://github.com/opencast/opencast-docker/blob/d16eedb0a0f6e69d905ef9e43be6cfb28dc145ce/rootfs/opencast/docker/scripts/helper.sh#L57):

```
error: missing Opencast ACTIVEMQ_BROKER_URL environment variables
  Did you forget to -e ACTIVEMQ_BROKER_URL=value ?
```

**Comment by mtneug** [comment]
This is now fixed with eae297083c6b013d4523b26271c84cb0adeea26e.
