### ISSUE TITLE
Add HEALTHCHECK

### ISSUE THREAD

**Issue by mtneug** [opencast/opencast-docker#21]
Since Docker 1.12 there are some new commands for Dockerfiles. [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#/healthcheck) let you define a command for testing if your application is healthy. It is planed to use this in the Swarm load balancer in Docker 1.13.

**Comment by lkiesow** [comment]
You might want to look at

- the health endpoint
- the message broker status endpoint

**Comment by JanKoppe** [comment]
@mtneug Take a look at my checks for the Health endpoint in the zabbix-agent config. I've done that for our monitoring already.
