### ISSUE TITLE
Not able to Modify `admin` User Details

### ISSUE THREAD

**Issue by andisugandi** [opencast/opencast-docker#213]
Hello all,

I am using [docker-compose/docker-compose.allinone.mariadb.yml](https://github.com/opencast/opencast-docker/blob/master/docker-compose/docker-compose.allinone.mariadb.yml) Docker compose file, and it is running on Docker Swarm Cluster.

I replace the MariaDB container image with: `mariadb:jammy`.

The Opencast apps is up and running successfully, except on changing the `admin` user details. It is said: `The user is not manageable`.

<img width="807" alt="Screenshot 2023-11-16 at 14 21 21" src="https://github.com/opencast/opencast-docker/assets/2184391/130ff92f-1d8d-4f4b-9447-d073fd340499">

---
1. Where to inspect the cause of the issue?
2. What work around should we take to modify the `admin` user details?

Thank you in advance.

**Comment by mtneug** [comment]
Hi @andisugandi 👋 

Opencast has different user providers. This `admin` user is created by the in-memory user provider based [on a configuration file](https://github.com/opencast/opencast/blob/f4db57cec6ea07438de1683a9e04c3c5920e6d4c/etc/custom.properties#L33-L41). Mount your adapted configuration file into the container to change the details.
