### ISSUE TITLE
No Opencast Series & Episode on Adding a new Video (Opencast) Activity Page

### ISSUE THREAD

**Issue by andisugandi** [opencast/opencast-docker#233]
Hi @mtneug and Team.

We are using [docker-compose/docker-compose.allinone.mariadb.yml](https://github.com/opencast/opencast-docker/blob/master/docker-compose/docker-compose.allinone.mariadb.yml) Docker compose file (version `16.4`), and it is running on Docker Swarm Cluster.

The series and events (episode) can be successfully added / uploaded via Moodle (version `4.3`) site (there are now: `Course_Series_99` and `Course_Series_100`), and those episodes can also be played both on Opencast studio/player and via embedded way.

### Moodle Opencast Videos Page
<img width="1112" alt="Screenshot 2024-09-14 at 11 52 58" src="https://github.com/user-attachments/assets/5b10166c-59b8-43d1-8d2e-6b33ff32afb9">

### Opencast Events & Series Page
<img width="1289" alt="Screenshot 2024-09-14 at 13 19 40" src="https://github.com/user-attachments/assets/4b8d0838-769b-4378-9309-c776d46b911e">

### Known Issue
<img width="1106" alt="Screenshot 2024-09-14 at 11 50 53" src="https://github.com/user-attachments/assets/64c226f3-39c8-4c1e-99e3-ac87dec13dae">

But the are **NO series and episodes** appear on the menu provided on Adding a new Video (Opencast) Activity page.

Needs help and suggestions.

Thank you in advance.

**Comment by mtneug** [comment]
Is this the course where the Moodle block was added? What publication channel did you configure for the activity plugin?

In general: this seems to be a configuration issue with the Moodle plugins and not related to the Opencast container images.

**Comment by mtneug** [comment]
I just created an example compose setup for Opencast + Moodle in this repository: https://github.com/opencast/community-integrations/tree/main/lms This is not a production example, but it might help you figure out your problem.

I will close this issue for now.
