### ISSUE TITLE
Let user choose uid/gid of the Opencast build user for the build image

### ISSUE THREAD

**Issue by mtneug** [opencast/opencast-docker#27]
Currently the `build` image builds Opencast as `root`. This leads to problems if files are shared via volumes with a local Docker user. Instead when starting a `build` container, users should be able to specify a uid/gid of a new user within the container. This new user must be able to become `root` again, as the Opencast startup scripts require.

**Comment by JanKoppe** [comment]
Check for some environment variable containing the UID, then use `su $RUN_UID -c '…'` for all commands that do not need to run as `root`? I don't think that this is particularly high priority though.

**Comment by mtneug** [comment]
@JanKoppe if you work on Opencast and compile as `root` you cannot change/remove the output files with the user outside of the container. It is confusing and undesirable to have to use `sudo`. I therefore wanted to add this function before describing the `build` image in the Opencast documentation.
