### ISSUE TITLE
Add an example for Docker Swarm mode

### ISSUE THREAD

**Issue by mtneug** [opencast/opencast-docker#32]

**Comment by BaddMann** [comment]
Any luck?

**Comment by mtneug** [comment]
Yes, the currently available images work as expected. The recent PRs added some features like health checking or a dynamic server URL, which are helpful for using Swarm. I used [these commands](https://gist.github.com/mtneug/af17ee2530b1088117b5a7528b91d86e) to start the services. `HOSTIP` can be any IP/hostname of a node in the cluster. `DIR` should point to the `docker-compose` directory of this repository.

I currently have little time to further write it up.  Also I would like to use the new [`docker stack` command](https://docs.docker.com/engine/reference/commandline/stack/), but hadn't yet the change to play around with Docker 1.13.

**Comment by mtneug** [comment]
I forgot to mention, the mounts must be available on all nodes. The script assumes you have a one node cluster and therefor uses volumes, which do not work across multiple hosts. Change it to bind mounts and point the `source` to a shared NFS directory if you have more nodes.

**Comment by mtneug** [comment]
People moved away from Docker Swarm and I never really got around to create an example. Let's close this.
