### ISSUE TITLE
Provide presentation-apache Image with stream security plugin?

### ISSUE THREAD

**Issue by JanKoppe** [opencast/opencast-docker#35]
I think it would be a good idea to provide an additional `presentation-apache` image that would include a Apache HTTP Server as a reverse proxy with the Stream Security plugin included.

**Comment by mtneug** [comment]
I'm somewhat reluctant to have containers that run two different services. Can't this be done with two containers? Maybe we can have a custom version of `httpd`, which is already configured for Opencast stream security?

**Comment by mtneug** [comment]
@JanKoppe can we close this issue or will you work on it? I would still argue to focus this repo on Opencast images only and if time allows create a new repo for Apache HTTP with preconfigured stream security.

**Comment by JanKoppe** [comment]
Let's close this issue for now, and build a separate image for such a use case - if there's time.
