### ISSUE TITLE
missing manifest for opencast/<distribution>4.0

### ISSUE THREAD

**Issue by sajkec** [opencast/opencast-docker#72]
example:
```
Pulling opencast (opencast/allinone:4.0)...
ERROR: manifest for opencast/allinone:4.0 not found
```
By looking at the DockerHub the only 4.x tag is 4.4, while the only official 4.x version of Opencast is 4.0 and this also reflects in the docker-compose versioning.

**Comment by mtneug** [comment]
Thank you @sajkec for reporting! This should indeed be 4.0, not sure why I called it 4.4 😕. I will fix this in the coming days.

**Comment by mtneug** [comment]
The branch is now renamed and builds for 4.0 are queued at Docker Hub.
