### ISSUE TITLE
Recent dockerhub builds fail because of --chown flag

### ISSUE THREAD

**Issue by dirkcgrunwald** [opencast/opencast-docker#83]
E.g. https://hub.docker.com/r/opencast/allinone/builds/b79ez8ydjprypysjzjgmhd6/

this is for the 4.3 / latest release. I can't see an error in the dockerfile but FYI.

**Comment by mtneug** [comment]
Thank you for the notice @dirkcgrunwald.

This [(among many other pain points)](https://groups.google.com/a/opencast.org/forum/#!topic/dev/Bs5m7HSaKD4) is one reason for the move to Quay. All images are now available there: <https://quay.io/organization/opencast/>.
