### ISSUE TITLE
Is the 'next' tag at quay.io rebuild periodically?

### ISSUE THREAD

**Issue by miesgre** [opencast/opencast-docker#99]
Is the 'next' tag rebuild periodically?
Can it be rebuild every night?

**Comment by mtneug** [comment]
Right now it is not. I will add an automation probably next week. For now, I manually triggered a rebuild.

**Comment by mtneug** [comment]
Opencast images are now rebuild automatically:

- `next`: daily
- `master`: weekly
- the last two minor versions of the latest major version: weekly
- the last two minor versions of the previously latest major version: weekly

I hope hat this will help to keep installed packages updated and continuously provide a `next` version.
